export interface TecidoInterface {
    id?: number,
    nome: string,
    composicao?: string,
    gramatura?: number,
    rendimento?: number,
    acabamento?: number,
    referencia?: number,
    avista?: number,
    prazo?: number,
    observacao?: string,
    image?: string,
    fornecedor?: string,
    fornecedorId?: number,
    created_at?: string,
    updated_at?: string,
}