export interface TecidoInterface {
    id?: number,
    nome: string,
    composicao?: string,
    gramatura?: number,
    rendimento?: number,
    acabamento?: number,
    referencia?: number,
    avista?: number,
    prazo?: number,
    observacao?: string,
    image?: string,

    caracteristica?: string,
    tecnologia?: string,
    favoritar?: number,
    prazoentrega?: number,
    prazodesenvolvimento?: number,

    uv?: number,
    dry?: number,
    insect?: number,
    smart?: number,
    defense?: number,
    chlomax?: number,
    hydro?: number,
    eco?: number,
    shield?: number,
    undertech?: number,
    ultraflex?: number,

    durabilidade?: number,
    toqueaveludado?: number,
    respirabilidade?: number,
    duplaface?: number,
    leveza?: number,
    altacobertura?: number,
    elasticidade?: number,
    secagemrapida?: number,
    toquegelado?: number,
    toquemacio?: number,
    toquedebrilho?: number,
    zerotransparencia?: number,
    naoesgarca?: number,
    naopinica?: number,
    oekotex?: number,
    compressao?: number,
    controledeodor?: number,

    fornecedor_id?: number,
    created_at?: string,
    updated_at?: string,
}