export interface TecidoInterface {
    id?: number,
    nome: string,
    composicao?: string,
    gramatura?: number,
    rendimento?: number,
    acabamento?: number,
    referencia?: number,
    avista?: number,
    prazo?: number,
    observacao?: string,
    image?: string,

    caracteristica?: string,
    tecnologia?: string,
    favoritar?: number,
    prazoentrega?: number,
    prazodesenvolvimento?: number,

    uv?: number,
    dry?: number,
    insect?: number,
    smart?: number,
    defense?: number,
    chlomax?: number,
    hydro?: number,
    eco?: number,
    shield?: number,
    undertech?: number,
    ultraflex?: number,

    fornecedor_id?: number,
    created_at?: string,
    updated_at?: string,
}